@host = http://localhost:5291




POST  {{host}}/Users/v1/api/Users
Content-Type:application/json

{
  
    "Name":"saeed mohammed al-abidi",
    "PasswordHash":"saeed!124",
    "UserName":"saeed1adm@Gmail.com",
    "linkedin":"https://www.linkedin.com/in/saeed-mohammed-al-obidi-289082147/"
     
 }

###

POST  {{host}}/Users/v1/api/Users/Roles
Content-Type:application/json

{
  
    "UserName":"saeed1adm@Gmail.com",
    "permissions":["read","write"]
     
 }

###

###

POST  {{host}}/Leads/v1/api/Leads
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtb2FoYW1tZWRAR21haWwuY29tIiwianRpIjoiOTIzM2IwODUtNTM0Yy00OTVjLTk1YTItNGVkNDRiN2IyOWQ0IiwiUGVybWlzc2lvbiI6WyJyZWFkIiwid3JpdGUiXSwiZXhwIjoxNzI0NDQwNTgwLCJpc3MiOiJZb3VySXNzdWVyIiwiYXVkIjoiWW91ckF1ZGllbmNlIn0.B0RW4x9NAltwyNXwttA1lWZROLkiK4KaP5M8G8RPX9k


{
    "Age":30,
    "Name":"saeed",
    "Email":"saeed1adm@Gmail.com",
    "Linkedin":"https://www.linkedin.com/in/saeed-mohammed-al-obidi-289082147/"
     
 }

###

 
 

GET {{host}}/Leads/v1/api/Leads/?leadId=3
Accept: application/json

###
//or 
GET {{host}}/Leads/v1/api/Leads/d/1
Accept: application/json

###

POST  {{host}}/Services/v1/api/Services
Content-Type:application/json

{
  "name": "subscription",
  "price": 100
}


###
POST  {{host}}/Applications/v1/api/Application
Content-Type:application/json

{
 "name": "Transfer the ASUS ROG G16 16-inch laptop to Saeed's address.",
  "leadId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "servicesId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
}
 