@host = http://localhost:5291
@Toekn =Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjEiLCJQZXJtaXNzaW9uIjpbImxlYWQucmVhZCIsImxlYWQud3JpdGUiLCJzZXJ2aWNlLnJlYWQiLCJzZXJ2aWNlLndyaXRlIiwiYXBwbGljYXRpb24ucmVhZCIsImFwcGxpY2F0aW9uLndyaXRlIiwidXNlci5yZWFkIiwidXNlci53cml0ZSJdLCJleHAiOjE3MjUwNDg4OTIsImlzcyI6IllvdXJJc3N1ZXIiLCJhdWQiOiJZb3VyQXVkaWVuY2UifQ.IoobiCqBAmrDnFnlaHLs-mrb0byyBQQKtcK5MbUut4M



POST  {{host}}/Users/v1/api/Users
Content-Type:application/json
Authorization: {{Toekn}}

{
  
    "Name":"saeed mohammed al-abidi",
    "PasswordHash":"saeed!124",
    "UserName":"saeed1adm@Gmail.com",
    "linkedin":"https://www.linkedin.com/in/saeed-mohammed-al-obidi-289082147/"
     
 }

###

POST  {{host}}/Users/v1/api/Users/Roles
Content-Type:application/json
Authorization: {{Toekn}}

{
  
    "UserName":"saeed1adm@Gmail.com",
    "permissions":["read","write"]
     
 }

###

POST  {{host}}/Users/v1/api/Users/Login
Content-Type:application/json

{
  
    "userName":"admin@example.com",
    "password":"saeed!123"
     
 }



###
POST {{host}}/Leads/v1/api/Leads
Content-Type: application/json
Authorization: {{Toekn}}

{
  "Age": 30,
  "Name": "Saeed",
  "Email": "saeed1adm@gmail.com",
  "Linkedin": "https://www.linkedin.com/in/saeed-mohammed-al-obidi-289082147/"
}


###

 
 

GET {{host}}/Leads/v1/api/Leads/?leadId=3
Accept: application/json
Authorization: {{Toekn}}

###
//or 
GET {{host}}/Leads/v1/api/Leads/d/1
Accept: application/json
Authorization: {{Toekn}}

###

POST  {{host}}/Services/v1/api/Services
Content-Type:application/json
Authorization: {{Toekn}}

{
  "name": "subscription",
  "price": 100
}


###
POST  {{host}}/Applications/v1/api/Application
Content-Type:application/json
Authorization: {{Toekn}}

{
 "name": "Transfer the ASUS ROG G16 16-inch laptop to Saeed's address.",
  "leadId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "servicesId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
}
 